### ISSUE TITLE
Could you please share the phenotype / metadata for the 4 paired 16S rRNA - metagenome datasets?

### ISSUE THREAD

**Issue by jialiu232** [bio-ontology-research-group/deepgometa#1]
Thanks for providing the SRR ids for the paired microbiome samples. But could you share the metadata information for these datasets as well please? Thanks!

**Comment by rund0wn** [comment]
Metadata is now uploaded here: https://github.com/bio-ontology-research-group/deepgometa/tree/main/PairedDatasets/Metadata
